project:
  type: website
  output-dir: docs

website:
  title: "Louise Rosenbaum"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: projects.qmd
      - sidebar:maps

sidebar:
    - id: maps
      title: "Maps Project"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual
