project:
  type: website
  output-dir: docs

website:
  title: "Louise Rosenbaum"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: mini_project2.qmd
      - sidebar:maps

  sidebar:
    - id: maps
      title: "Maps Project"
      contents:
        - WI_Gerrymandering.qmd
        - US_State_Pop.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual
