project:
  type: website
  output-dir: docs

website:
  title: "Louise Rosenbaum"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - sidebar:maps
      - file: mini_project2.qmd
      - file: mini_project3.qmd

  sidebar:
    - id: maps
      title: "Mini Project 1 - Maps Project"
      contents:
        - WI_Gerrymandering.qmd
        - US_State_Pop.qmd
        
  page-footer:
    left: |
      &copy; Louise Rosenbaum, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual
