---
title: "US States"
sidebar: false
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(readr)
library(tidyverse)
library(poliscidata)
```

```{r, include=FALSE}
library(maps)
us_states <- map_data("state")
head(us_states)

state_data <- as_tibble(poliscidata::states) |>
  mutate(state_name = str_squish(str_to_lower(as.character(state)))) |>
  select(-state)
print(state_data, n = 5, width = Inf)
```

```{r, echo=FALSE, message=FALSE}
unemployment_data <- left_join(us_states, state_data, by = c("region" = "state_name"))

ggplot(unemployment_data, aes(x = long, 
                              y = lat, 
                              group = group, 
                              fill = unemploy)) +
  geom_polygon(color = "white") +
  scale_fill_gradient(low = "yellow", 
                      high = "red", 
                      name = "Unemployment Rate (%)") +
  labs(title = "Unemployment Rate by State", x = "", y = "") +
  coord_fixed(1.3) +
  theme_void() +
  theme(legend.position = "right")
```
